Найдите посредством NumPy SVD для матрицы:

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$


             
Для матрицы из предыдущего задания найдите:

а) евклидову норму;

б) норму Фробениуса.

In [2]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

In [13]:
A = np.array([[1, 2, 0],
              [0, 0, 5],
              [3, -4, 2],
              [1, 6, 5],
              [0, 1, 0]])

r = np.linalg.matrix_rank(A)

print(f'Матрица A:\n{A}')
print ("Ранг матрицы:", r)

Матрица A:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]
Ранг матрицы: 3


In [8]:
U, s, W = np.linalg.svd(A)

# Транспонируем матрицу W
V = W.T

# s - список диагональных элементов, его нужно привести к виду диагональной матрицы для наглядности
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s
print (f'Матрица U:\n{U}')
print (f'Матрица D:\n{D}')
print (f'Матрица V:\n{V}')

Матрица U:
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]
Матрица D:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]
Матрица V:
[[ 0.07 -0.37 -0.93]
 [ 0.72  0.67 -0.21]
 [ 0.69 -0.65  0.31]]


Проверка

In [15]:
print(np.dot(U.T, U))

[[ 1. -0.  0.  0.  0.]
 [-0.  1. -0. -0. -0.]
 [ 0. -0.  1.  0. -0.]
 [ 0. -0.  0.  1. -0.]
 [ 0. -0. -0. -0.  1.]]


In [16]:
print(np.dot(V.T, V))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
print(np.dot(np.dot(U, D), V.T))

[[ 1.  2. -0.]
 [-0.  0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [ 0.  1.  0.]]


Найдем Евклидову норму

Так как,евклидова норма матрицы равна евклидовой норме диагональной матрицы из её сингулярных чисел  𝐷 . 
Максимальное значение полученного отношения будет равно максимальному сингулярному числу  𝜇𝑚𝑎𝑥 , и, принимая во внимание факт сортировки по убыванию сингулярных чисел, получим:

‖𝐴‖𝐸=𝜇1.

отсюда:
𝜇1 = 8,82

In [18]:
print (f'Матрица D:\n{D}')

Матрица D:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]


Евклидова норма данной матрицы равна 8,82

Найдем норму Фробениуса

In [19]:
X = np.linalg.norm(A)

In [20]:
print(X)

11.045361017187261
